CREATE TABLE IF NOT EXISTS Tasks (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(255) NOT NULL,
    Description TEXT,
    Status VARCHAR(50) DEFAULT 'todo',
    Priority VARCHAR(50) DEFAULT 'low',
    CategoryId VARCHAR(255),
    DueDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);